# FILE NAMES
FILE_NAMES:
  RAW:
    2019: 'TED_SD_RAW_2019'
    2020: 'TED_SD_RAW_2020'
  CLEAN: 'TED_SD_CLEAN'
  DESCRIBE: "TED_SD_CLEAN_DESCRIPTION"
  ENHANCED: "TED_SD_ENHANCED"
  ENHANCED_TARGET_COL: "TD_SD_ENH_TARGET_COL"
  MODEL: "TD_SD_FINAL"
# File Separators
FILE_SEP:
  ted_sd_raw_2019: ','
  ted_sd_raw_2020: ','
  TED_SD_CLEAN: ','
# DATASET ENHANCEMENTS
IN_OUT_COL_MAPPING:
  1: "1"
  2: "2"
  3: "Inpatient"
  4: "Inpatient"
  5: "Inpatient"
  6: "Outpatient"
  7: "Outpatient"
  8: "Outpatient"
  null: null
IN_OUT_COL_NAMES:
  IN: "SERVICES_D"
  OUT: "IN_OUT"
# Map Current Null Value to New Null Value
NULL_MAPPER:
  FROM: -9
  TO: null
DROP_COLUMNS:
  NULL_PCT_THRESHOLD: 0.7
# COLUMN DATA TYPE GROUPS
DATA_TYPE_CATEGORIES:
  ID:
  - CASEID
  TARGET:
  - TARGET
  NOMINAL_BINARY:
  - ALCFLG
  - AMPHFLG
  - BENZFLG
  - COKEFLG
  - HALLFLG
  - IDU
  - INHFLG
  - MARFLG
  - METHFLG
  - METHUSE
  - MTHAMFLG
  - NOPRIOR
  - OPSYNFLG
  - OTCFLG
  - OTHERFLG
  - PCPFLG
  - PREG
  - PSYPROB
  - SEDHPFLG
  - STIMFLG
  - TRNQFLG
  - VET
  NOMINAL:
  - ALCDRUG
  - ARRESTS
  - ARRESTS_D
  - BARBFLG
  - CBSA2010
  - DIVISION
  - DSMCRIT
  - EMPLOY
  - EMPLOY_D
  - ETHNIC
  - GENDER
  - HERFLG
  - HLTHINS
  - LIVARAG
  - LIVARAG_D
  - MARSTAT
  - PRIMINC
  - PRIMPAY
  - PSOURCE
  - RACE
  - REASON
  - REGION
  - ROUTE1
  - ROUTE2
  - SERVICES
  - SERVICES_D
  - STFIPS
  - SUB1
  - SUB1_D
  - SUB2
  - SUB2_D
  - SUB3
  - SUB3_D
  - DETLNF
  - DETNLF_D
  - DETCRIM
  NUMERIC_ORDINAL:
  - AGE
  - DAYWAIT
  - DISYR
  - EDUC
  - FREQ_ATND_SELF_HELP
  - FREQ_ATND_SELF_HELP_D
  - FREQ1
  - FREQ1_D
  - FREQ2
  - FREQ2_D
  - FRSTUSE1
  - FRSTUSE2
  - LOS
  - FREQ3
  - FRSTUSE3
# CORRELATION MATRIX FEATURES (All Numeric or Cat Ordinal)
FEATURE_IMPORTANCE:
  CORR_MATRIX_FEATURES:
    - AGE
    - DAYWAIT
    - EDUC
    - FREQ_ATND_SELF_HELP
    - FREQ_ATND_SELF_HELP_D
    - FREQ1
    - FREQ1_D
    - FREQ2
    - FREQ2_D
    - FRSTUSE1
    - FRSTUSE2
  CHI2:
    - ALCFLG
    - AMPHFLG
    - BENZFLG
    - COKEFLG
    - HALLFLG
    - IDU
    - INHFLG
    - MARFLG
    - METHFLG
    - METHUSE
    - MTHAMFLG
    - NOPRIOR
    - OPSYNFLG
    - OTCFLG
    - OTHERFLG
    - PCPFLG
    - PREG
    - PSYPROB
    - SEDHPFLG
    - STIMFLG
    - TRNQFLG
    - VET
    - ALCDRUG
    - ARRESTS
    - ARRESTS_D
    - BARBFLG
    - CBSA2010
    - DIVISION
    - DSMCRIT
    - EMPLOY
    - EMPLOY_D
    - ETHNIC
    - GENDER
    - HERFLG
    - HLTHINS
    - LIVARAG
    - LIVARAG_D
    - MARSTAT
    - PRIMINC
    - PRIMPAY
    - PSOURCE
    - RACE
    - REASON
    - REGION
    - ROUTE1
    - ROUTE2
    - STFIPS
    - SUB1
    - SUB1_D
    - SUB2
    - SUB2_D
    - SUB3
    - SUB3_D
    - TARGET
  MODELS:
    - ALCFLG
    - AMPHFLG
    - BENZFLG
    - COKEFLG
    - HALLFLG
    - IDU
    - INHFLG
    - MARFLG
    - METHFLG
    - METHUSE
    - MTHAMFLG
    - NOPRIOR
    - OPSYNFLG
    - OTCFLG
    - OTHERFLG
    - PCPFLG
    - PREG
    - PSYPROB
    - SEDHPFLG
    - STIMFLG
    - TRNQFLG
    - VET
    - ALCDRUG
    - ARRESTS
    - ARRESTS_D
    - BARBFLG
    - CBSA2010
    - DIVISION
    - DSMCRIT
    - EMPLOY
    - EMPLOY_D
    - ETHNIC
    - GENDER
    - HERFLG
    - HLTHINS
    - LIVARAG
    - LIVARAG_D
    - MARSTAT
    - PRIMINC
    - PRIMPAY
    - PSOURCE
    - RACE
    - REASON
    - REGION
    - ROUTE1
    - ROUTE2
    - STFIPS
    - SUB1
    - SUB1_D
    - SUB2
    - SUB2_D
    - SUB3
    - SUB3_D
    - AGE
    - DAYWAIT
    - DISYR
    - EDUC
    - FREQ_ATND_SELF_HELP
    - FREQ_ATND_SELF_HELP_D
    - FREQ1
    - FREQ1_D
    - FREQ2
    - FREQ2_D
    - FRSTUSE1
    - FRSTUSE2
    - TARGET
ML_MODEL_FEATURE_SET:
  - CASEID
  - ALCFLG
  - AMPHFLG
  - BENZFLG
  - COKEFLG
  - HALLFLG
  - IDU
  - INHFLG
  - MARFLG
  - METHFLG
  - METHUSE
  - MTHAMFLG
  - NOPRIOR
  - OPSYNFLG
  - OTCFLG
  - OTHERFLG
  - PCPFLG
  - PREG
  - PSYPROB
  - SEDHPFLG
  - STIMFLG
  - TRNQFLG
  - VET
  - ALCDRUG
  - ARRESTS
  - ARRESTS_D
  - BARBFLG
  - CBSA2010
  - DIVISION
  - DSMCRIT
  - EMPLOY
  - EMPLOY_D
  - ETHNIC
  - GENDER
  - HERFLG
  - HLTHINS
  - LIVARAG
  - LIVARAG_D
  - MARSTAT
  - PRIMINC
  - PRIMPAY
  - PSOURCE
  - RACE
  - REASON
  - REGION
  - ROUTE1
  - ROUTE2
  - STFIPS
  - SUB1
  - SUB1_D
  - SUB2
  - SUB2_D
  - SUB3
  - SUB3_D
  - AGE
  - DAYWAIT
  - EDUC
  - FREQ_ATND_SELF_HELP
  - FREQ_ATND_SELF_HELP_D
  - FREQ1
  - FREQ1_D
  - FREQ2
  - FREQ2_D
  - FRSTUSE1
  - FRSTUSE2
  - TARGET
COLUMNS_NOT_IN_FINAL_FEATURE_SET:
  TARGET_LEAKAGE:
    - LOS
    - SERVICE_D
    - SERVICES
    - IN_OUT
  UNIQUENESS:
    - DISYR
  NULL_PCT:
    - FREQ3_D
    - DETCRIM
    - FREQ3
    - FRSTUSE3
    - ROUTE3
    - DETLNF
    - DETNLF_D
  FEATURE_IMPORTANCE:
    - ''
